# This plugin will get data files with a GET call and store them with a PUT call
# Data files are files which end with "{fileName}.data.yaml" for plugins
#
# If you need authentication you could adjust the template to something like this:
#    urlTemplate: "https://myserver.com/get.php?file={componentId}.{fileName}?token=<yourtoken>"
#
# If you are hosting your files directly as yaml without a php file you should use it like this
#    urlTemplate: "https://myserver.com/{componentId}.{fileName}.yaml"
#
# Variables:
#   {componentId}: the plugin or component which is reading or storing data (example values: OpenMod.Core, Kr4ken.NewEssentials)
#   {fileName}: the file name, keep in mind that it is not unique and must be used with componentId when storing (example values: roles, users, etc.)
# An example sync file name would be {componentId}:{fileName} -> OpenMod.Core:users

urlTemplate: 'https://myserver.com/get.php?file={componentId}.{fileName}'

syncedFiles:
- name: "OpenMod.Core:roles" # sync roles
- name: "OpenMod.Core:users" # sync user roles, data and permissions

# If you don't know what componentId or fileName to use, check your logs for "Loading data file locally: XXX.XXX" or "Saving data file locally: XXX.XXX" messages.